apiVersion: v1
kind: Service
metadata:
  name: micro-api
  namespace: default
  labels:
    name: micro-api
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
  selector:
    name: micro-api
  type: LoadBalancer
