app: xxx

mysql:
  enabled: true
  url: root:123456@tcp(127.0.0.1:3306)/micro_test?charset=utf8&parseTime=true&loc=Asia%2FShanghai
  maxidleconnection: 100
  maxopenconnection: 130

etcds:
  -
    enabled: false
    host: "127.0.0.1"
    port: 2379
  -
    enabled: true
    host: "127.0.0.1"
    port: 2379